database:
  uri: "mongodb://root:root@localhost:27017/"
  database: "analytics"
  timeout: 20

server:
  host: "localhost"
  port: "8080"

AllowedHost: "https://luqmansen.github.io"

AllowedRequest:
  - "https://luqmansen.github.io"
  - "http://localhost:8080"

